language: python
python:
    - "3.8"
service:
  - docker
before_install:
  - docker build -t jedidiahjohnnagarajan/flaskdocker1 -f app/Dockerfile.dev ./app
script:
  docker run jedidiahjohnnagarajan/flaskdocker1 pytest test
